on:
  push:
    branches:
      - main

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          [
            { name: chat-projection, file: projections/chat/Dockerfile },
            { name: chat-aggregate, file: aggregates/chat/Dockerfile },
            # { name: chat-client, file: apps/chat-client/Dockerfile },
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set outputs
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: maxrsb/${{ matrix.app.name }}:${{ steps.sha.outputs.short }}, maxrsb/${{ matrix.app.name }}:latest
          file: ${{ matrix.app.file }}
          context: .
